/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AiTutorRouteImport } from './routes/ai-tutor'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as InstructorRouteImport } from './routes/instructor'
import { Route as MistakesRouteImport } from './routes/mistakes'
import { Route as PeriodicTableRouteImport } from './routes/periodic-table'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as ExamsIndexRouteImport } from './routes/exams.index'
import { Route as ExamsSlugRouteImport } from './routes/exams.$slug'
import { Route as CoursesSlugIndexRouteImport } from './routes/courses.$slug.index'
import { Route as CoursesSlugLessonsLessonSlugRouteImport } from './routes/courses.$slug.lessons.$lessonSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AiTutorRoute = AiTutorRouteImport.update({
  id: '/ai-tutor',
  path: '/ai-tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorRoute = InstructorRouteImport.update({
  id: '/instructor',
  path: '/instructor',
  getParentRoute: () => rootRouteImport,
} as any)
const MistakesRoute = MistakesRouteImport.update({
  id: '/mistakes',
  path: '/mistakes',
  getParentRoute: () => rootRouteImport,
} as any)
const PeriodicTableRoute = PeriodicTableRouteImport.update({
  id: '/periodic-table',
  path: '/periodic-table',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsIndexRoute = ExamsIndexRouteImport.update({
  id: '/exams/',
  path: '/exams/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsSlugRoute = ExamsSlugRouteImport.update({
  id: '/exams/$slug',
  path: '/exams/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugIndexRoute = CoursesSlugIndexRouteImport.update({
  id: '/courses/$slug/',
  path: '/courses/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugLessonsLessonSlugRoute =
  CoursesSlugLessonsLessonSlugRouteImport.update({
    id: '/courses/$slug/lessons/$lessonSlug',
    path: '/courses/$slug/lessons/$lessonSlug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/ai-tutor': typeof AiTutorRoute
  '/auth': typeof AuthRoute
  '/connect': typeof ConnectRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/instructor': typeof InstructorRoute
  '/mistakes': typeof MistakesRoute
  '/periodic-table': typeof PeriodicTableRoute
  '/tools': typeof ToolsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/exams/$slug': typeof ExamsSlugRoute
  '/articles/': typeof ArticlesIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/exams/': typeof ExamsIndexRoute
  '/courses/$slug/': typeof CoursesSlugIndexRoute
  '/courses/$slug/lessons/$lessonSlug': typeof CoursesSlugLessonsLessonSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/ai-tutor': typeof AiTutorRoute
  '/auth': typeof AuthRoute
  '/connect': typeof ConnectRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/instructor': typeof InstructorRoute
  '/mistakes': typeof MistakesRoute
  '/periodic-table': typeof PeriodicTableRoute
  '/tools': typeof ToolsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/exams/$slug': typeof ExamsSlugRoute
  '/articles': typeof ArticlesIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/exams': typeof ExamsIndexRoute
  '/courses/$slug': typeof CoursesSlugIndexRoute
  '/courses/$slug/lessons/$lessonSlug': typeof CoursesSlugLessonsLessonSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/ai-tutor': typeof AiTutorRoute
  '/auth': typeof AuthRoute
  '/connect': typeof ConnectRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/instructor': typeof InstructorRoute
  '/mistakes': typeof MistakesRoute
  '/periodic-table': typeof PeriodicTableRoute
  '/tools': typeof ToolsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/exams/$slug': typeof ExamsSlugRoute
  '/articles/': typeof ArticlesIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/exams/': typeof ExamsIndexRoute
  '/courses/$slug/': typeof CoursesSlugIndexRoute
  '/courses/$slug/lessons/$lessonSlug': typeof CoursesSlugLessonsLessonSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/ai-tutor'
    | '/auth'
    | '/connect'
    | '/contact'
    | '/dashboard'
    | '/instructor'
    | '/mistakes'
    | '/periodic-table'
    | '/tools'
    | '/articles/$slug'
    | '/exams/$slug'
    | '/articles/'
    | '/courses/'
    | '/exams/'
    | '/courses/$slug/'
    | '/courses/$slug/lessons/$lessonSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/ai-tutor'
    | '/auth'
    | '/connect'
    | '/contact'
    | '/dashboard'
    | '/instructor'
    | '/mistakes'
    | '/periodic-table'
    | '/tools'
    | '/articles/$slug'
    | '/exams/$slug'
    | '/articles'
    | '/courses'
    | '/exams'
    | '/courses/$slug'
    | '/courses/$slug/lessons/$lessonSlug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/ai-tutor'
    | '/auth'
    | '/connect'
    | '/contact'
    | '/dashboard'
    | '/instructor'
    | '/mistakes'
    | '/periodic-table'
    | '/tools'
    | '/articles/$slug'
    | '/exams/$slug'
    | '/articles/'
    | '/courses/'
    | '/exams/'
    | '/courses/$slug/'
    | '/courses/$slug/lessons/$lessonSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AiTutorRoute: typeof AiTutorRoute
  AuthRoute: typeof AuthRoute
  ConnectRoute: typeof ConnectRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  InstructorRoute: typeof InstructorRoute
  MistakesRoute: typeof MistakesRoute
  PeriodicTableRoute: typeof PeriodicTableRoute
  ToolsRoute: typeof ToolsRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  ExamsSlugRoute: typeof ExamsSlugRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  ExamsIndexRoute: typeof ExamsIndexRoute
  CoursesSlugIndexRoute: typeof CoursesSlugIndexRoute
  CoursesSlugLessonsLessonSlugRoute: typeof CoursesSlugLessonsLessonSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-tutor': {
      id: '/ai-tutor'
      path: '/ai-tutor'
      fullPath: '/ai-tutor'
      preLoaderRoute: typeof AiTutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor': {
      id: '/instructor'
      path: '/instructor'
      fullPath: '/instructor'
      preLoaderRoute: typeof InstructorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mistakes': {
      id: '/mistakes'
      path: '/mistakes'
      fullPath: '/mistakes'
      preLoaderRoute: typeof MistakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/periodic-table': {
      id: '/periodic-table'
      path: '/periodic-table'
      fullPath: '/periodic-table'
      preLoaderRoute: typeof PeriodicTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams/': {
      id: '/exams/'
      path: '/exams'
      fullPath: '/exams/'
      preLoaderRoute: typeof ExamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams/$slug': {
      id: '/exams/$slug'
      path: '/exams/$slug'
      fullPath: '/exams/$slug'
      preLoaderRoute: typeof ExamsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug/': {
      id: '/courses/$slug/'
      path: '/courses/$slug'
      fullPath: '/courses/$slug/'
      preLoaderRoute: typeof CoursesSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug/lessons/$lessonSlug': {
      id: '/courses/$slug/lessons/$lessonSlug'
      path: '/courses/$slug/lessons/$lessonSlug'
      fullPath: '/courses/$slug/lessons/$lessonSlug'
      preLoaderRoute: typeof CoursesSlugLessonsLessonSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AiTutorRoute: AiTutorRoute,
  AuthRoute: AuthRoute,
  ConnectRoute: ConnectRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  InstructorRoute: InstructorRoute,
  MistakesRoute: MistakesRoute,
  PeriodicTableRoute: PeriodicTableRoute,
  ToolsRoute: ToolsRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  ExamsSlugRoute: ExamsSlugRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  ExamsIndexRoute: ExamsIndexRoute,
  CoursesSlugIndexRoute: CoursesSlugIndexRoute,
  CoursesSlugLessonsLessonSlugRoute: CoursesSlugLessonsLessonSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
